// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Yjn8cDvxsB0iGVgtUtOcWmRV7S-pPlA',
    appId: '1:679930430701:web:aa824a34e44a076e5778e4',
    messagingSenderId: '679930430701',
    projectId: 'carmind-46f12',
    authDomain: 'carmind-46f12.firebaseapp.com',
    storageBucket: 'carmind-46f12.appspot.com',
    measurementId: 'G-N1NZ346BK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYQRfZL-FjgdDzGPcUDR6_ghl7AsCplQ',
    appId: '1:679930430701:android:1370e00aa59b07605778e4',
    messagingSenderId: '679930430701',
    projectId: 'carmind-46f12',
    storageBucket: 'carmind-46f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3TkERpX7AMvqZixOVMQKWBtbypF8VFk',
    appId: '1:679930430701:ios:654b02b3352571eb5778e4',
    messagingSenderId: '679930430701',
    projectId: 'carmind-46f12',
    storageBucket: 'carmind-46f12.appspot.com',
    iosClientId: '679930430701-mqnk9up7rrb66bp0ohm1bchso29ekh1g.apps.googleusercontent.com',
    iosBundleId: 'com.mindia.carmind-app',
  );
}
